baseurl         = "//www.krystalandjose.com"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
# Added for publishing on Github Pages
publishDir = "docs"
# SectionPagesMenu = "main"
# canonifyurls    = true
title = "Krystal & Jose"

[params]
  title = "Krystal & Jose"
  subtitle    = ""
  copyright   = "© 2018"

  cover       = "img/main-cover.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []

  author = "Krystal & Jose"
  authorAvatar = "img/author-avatar.jpg"
  authorLocation = "Denver, CO"
  authorWebsite = "https://www.krystalandjose.com"
  authorDescription = "Author"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 100

[[menu.main]]
  name = "Wedding Photos"
  url = "/wedding-photos/"
  weight = 99
